productlist:
  title: Product list
  desctiption: Shows products on a page
  icon: icon-picture
  settings:
    fields:
      tags:
        type: tags
        tagsType: Content
        title: Tags
      displayMode:
        type: select
        title: Display mode
        options:
          - view:List
          - featured:Featured
      cols:
        type: select
        title: Columns
        options:
          - 1
          - 2
          - 3
          - 4
          - 6
